---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Add Docker apt key and repository
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Ensure directory exists for /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
      become: true

    - name: Add Docker apt key
      ansible.builtin.get_url:
        url: "{{ docker_apt_gpg_key }}"
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: false
        checksum: "{{ docker_apt_gpg_key_checksum | default(omit) }}"
      register: add_repository_key
      ignore_errors: "{{ docker_apt_ignore_key_error }}"
      become: true

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        filename: "{{ docker_apt_filename }}"
        update_cache: true
      become: true

- name: Install docker dependencies via apt
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    # These are unofficial distrobutions of Docker that can cause conflicting packages
    # See https://docs.docker.com/engine/install/debian/#uninstall-old-versions
    - name: Ensure old versions of Docker are not installed
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-engine
          - podman-docker
          - containerd
          - runc
        state: absent
      become: true

    - name: Ensure docker dependencies are installed
      ansible.builtin.apt:
        name: "{{ docker_dep_pkgs }}"
        state: present
      become: true
